"""add totals and schedule to simulations

Revision ID: ff0224340046
Revises: 136f36b4b18c
Create Date: 2026-02-03 04:28:10.822883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0224340046'
down_revision: Union[str, Sequence[str], None] = '136f36b4b18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('payment', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('simulations', sa.Column('total_interest', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('simulations', sa.Column('total_payment', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('simulations', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'schedule')
    op.drop_column('simulations', 'total_payment')
    op.drop_column('simulations', 'total_interest')
    op.drop_column('simulations', 'payment')
    # ### end Alembic commands ###
